alias nand="cd /home/nand"
alias andre="cd /mnt/c/User/andre"
alias vimrc="nand; vim .vimrc"
alias bashrc="nand; vim .bashrc"
alias bash_aliases="nand; vim .bash_aliases"
alias andre="cd /mnt/c/Users/andre"
alias vimfiles="andre; cd vimfiles"
#alias microelectronics="ssh ms17.20@led-x3850-2.polito.it -p 10018"
alias lsa="ls -a"
alias ..="cd .."
alias workspace="cd /mnt/c/Workspace"
alias cluster="ssh agualc2@login-1.extreme.acer.uic.edu"
alias jump="ssh agualco@jump.ece.uic.edu"
alias display="export DISPLAY=:0"
